version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres-comp
    volumes:
      - PostgresData
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=workdb
    restart: unless-stopped
#  # APP*****************************************
  employee-app:
    image: employee-app-comp:latest
    network_mode: bridge
    container_name: employeeapp-comp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      JDBC_DATABASE_URL: 'jdbc:postgresql://127.0.0.1:5432/workdb'
volumes:
  PostgresData: